# We override the default clone step to workaround a bug with GitHub (see #3415)
clone:
  clone:
    image: plugins/git
    commands:
      - sleep 5s
      - git init
      - git remote add origin $DRONE_REMOTE_URL
      - git fetch --no-tags origin $DRONE_COMMIT_REF
      - if [ $DRONE_BUILD_EVENT = "push" ]; then git reset --hard -q $DRONE_COMMIT_SHA; else git checkout -qf FETCH_HEAD; fi
      - git submodule update --init --recursive

pipeline:
  # TESTS:
  # We run tests in parallel. Tests run in a copy of the working directory to avoid conflict
  test:
    group: test
    image: lampepfl/dotty:2017-11-17
    commands:
      - cp -R . /tmp/1/ && cd /tmp/1/
      - ./project/scripts/sbt ";compile ;test-only -- --tests=compilePos"

  test_bootstrapped:
    group: test
    image: lampepfl/dotty:2017-11-17
    commands:
      - cp -R . /tmp/2/ && cd /tmp/2/
      - ./project/scripts/sbt ";dotty-bootstrapped/compile ;dotty-bootstrapped/test-only -- --tests=compilePos"

  # PUBLISHING:
  # Publishing expect NIGHTLYBUILD or RELEASEBUILD to be set. See dottyVersion in Build.scala
  publish_nightly:
    image: lampepfl/dotty:2017-11-17
    environment:
      - NIGHTLYBUILD=yes
    commands:
      - ./project/scripts/sbtPublish ";dotty-bootstrapped/publishSigned ;sonatypeRelease"
    secrets: [ sonatype_user, sonatype_pw, pgp_pw, pgp_secret ]
    when:
      event: deployment
      environment: nightly

  publish_release:
    image: lampepfl/dotty:2017-11-17
    environment:
      - RELEASEBUILD=yes
    commands:
      # Produces dotty-version.{tar.gz, zip}
      - ./project/scripts/sbt dist-bootstrapped/packArchive
      - ./project/scripts/sbtPublish ";dotty-bootstrapped/publishSigned ;sonatypeRelease"
    secrets: [ sonatype_user, sonatype_pw, pgp_pw, pgp_secret ]
    when:
      event: tag

  # Publish dotty-version.{tar.gz, zip} to GitHub Release
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    draft: true
    files:
      - dist-bootstrapped/target/dotty-*
    checksum:
      - sha256
    when:
      event: tag

  publish_sbt_release:
    image: lampepfl/dotty:2017-11-17
    environment:
      - RELEASEBUILD=yes
    commands:
      - ./project/scripts/sbtPublish ";sbt-dotty/publishSigned ;sonatypeRelease"
    secrets: [ sonatype_user, sonatype_pw, pgp_pw, pgp_secret ]
    when:
      event: deployment
      environment: sbt_release

  # NOTIFICATIONS:
  slack:
    image: plugins/slack
    channel: dotty
    secrets: [ slack_webhook ]
    when:
      status: [ failure ]
      event: [ push, tag, deployment ]

branches:
  # The gh-pages branch holds the documentation and don't need to be built
  exclude: gh-pages
